services:
  # ----------------
  # MinIO (S3 Storage)
  # ----------------
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # ----------------
  # Airflow (Orchestration)
  # ----------------
  airflow:
    image: apache/airflow:2.8.3
    container_name: airflow
    restart: always
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/airflow.db
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Zia --lastname Arz --role Admin --email admin@example.com &&
               airflow webserver & airflow scheduler"
    volumes:
      - ./dags:/opt/airflow/dags

volumes:
  minio_data:
